import { Montserrat, Lato } from "next/font/google";
import Header from "./componets/principal/Header";
import Footer from "./componets/principal/Footer";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-monserrat",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Onovatech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${lato.variable} antialiased`}
      >
        <Header /> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
